In [12]:
# numpy
# axis
import numpy as np

m = [[1,2,3,4],[6,7,8,9],[0,8,4,1],[3,6,5,4]]
mat = np.array(m)

mat[2:,2:]
mat[[0,2],1:3]

v = [1,23,5,3,3,5,7]
vec = np.array(v)
vec

vec.sum()
vec.mean()
vec.max()
vec.min()
vec.var()   # 분산
vec.std()   # 표준편차

# mat에 sum, mean, max, min, std, var

m = [[1,2,3,4],[6,7,8,9],[0,8,4,1],[3,6,5,4]]
mat = np.array(m)

mat.sum()

# (행,열) => 행 :0 . 열 : 1
mat.sum(axis=0) # row
mat.sum(axis=1) # colum

mat.max(axis=0)
mat.max(axis=1)

array([4, 9, 8, 6])

In [16]:

# 행렬 -> Indexing [행 index, 열 index]

# 데이터의 일반기준
# 행 => row -> 개별 데이터(학생1, 학생2..) -> 개별 데이터
# 열 => column -> 데이터의 특징(이름, 키, 주소, 나이) -> 데이터 특성값 / feather

# numpy의 연산의 특징 : 원소끼리 연산을 한다
# element wise operation
vec1 = np.array([1,1,1,1,1,1,1])

vec1 + vec

vec + 1

array([ 2, 24,  6,  4,  4,  6,  8])

In [18]:
vec2 = np.array([1,2])

vec2

array([1, 2])

In [20]:
# broadcasting
# shape이 다른 array 간의 연산을 하는 경우, shape이 작은 array의 shape이 확장이 되어서
# 동일한 shape를 만들고
# element wise(원소끼리 연산)을 수행한다..

vec + 1
np.array([2,24,6,4,4,4,6]) + np.array([1,1,1,1,1,1,1]) # broadcasting

array([ 3, 25,  7,  5,  5,  5,  7])

In [26]:
mat1 = np.array([[1,2,3,4],[5,6,7,8]])
mat2 = np.array([[0,2,3,0],[7,8,9,3]])

mat1 + mat2
mat1 * mat2
mat1 - mat2

vec1 = np.array([5,4,2,7])
vec1.shape

mat2 + vec1 # broadcasting

array([[ 5,  6,  5,  7],
       [12, 12, 11, 10]])

In [27]:
np.array([[5,4,2,7],[5,4,2,7]])

array([[5, 4, 2, 7],
       [5, 4, 2, 7]])

In [28]:
vec2 = np.array([2,45,6,7,4,3,2,34,23,4])

# vec2에서 10보다 큰 값만 출력
vec2 > 10 # broadcasting

array([False,  True, False, False, False, False, False,  True,  True,
       False])

In [29]:
vec2[vec2>10]

array([45, 34, 23])

In [48]:
# 비교연산도 element wise operation을 함(원소끼리 연산..)

# vec2에서 홀수만 출력
vec2[vec2 %2 != 0]

# 1 ~ 100까지의 정수에서 20보다 크고 70보다 작은 3의 배수들을 출력하시오..
# np.array를 사용..

vec3 = np.arange(1,101)
vec3[(vec3 > 20) & (vec3 < 70) & (vec3 % 3 == 0)]


array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69])

## Pandas

In [55]:
import pandas as pd
import numpy as np

raw_data = {
    'first_name' : ['Jason', 'Molly', 'Tina', 'Jake', 'Any'],
    'last_name' : ['Miller', 'jacobson', 'Ali', 'Milner', 'Cooze'],
    'age' : [43,53,36,24,73],
    'city' : ['San Francisco', 'Baltimore', 'Miami','Douglas','Boston']
}

df = pd.DataFrame(raw_data)
df

first_name last_name  age           city
0      Jason    Miller   43  San Francisco
1      Molly  jacobson   53      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Any     Cooze   73         Boston

In [56]:
# index와 Column 자리바꾸기
df.transpose()

0          1      2        3       4
first_name          Jason      Molly   Tina     Jake     Any
last_name          Miller   jacobson    Ali   Milner   Cooze
age                    43         53     36       24      73
city        San Francisco  Baltimore  Miami  Douglas  Boston

In [57]:
# 삭제
#del df['city']         # 원본 반영
#df.drop(1,axis = 0)
df.drop(2)                  # default : axis = 0
df.drop(3, inplace=True)    # inplace 원본 반영
df.drop('age')
df.drop(['first_name','age'], axis=1, inplace=True)

first_name last_name  age           city
0      Jason    Miller   43  San Francisco
1      Molly  jacobson   53      Baltimore
3       Jake    Milner   24        Douglas
4        Any     Cooze   73         Boston

In [58]:
# 나이가 70 이상인 사람이 사는 도시를 출력
df.loc[df.age > 70].city

4    Boston
Name: city, dtype: object

In [61]:
list(df.index)
df.columns

Index(['first_name', 'last_name', 'age', 'city'], dtype='object')

In [62]:
df.columns = ['fn','ln','age','city']
df

fn        ln  age           city
0  Jason    Miller   43  San Francisco
1  Molly  jacobson   53      Baltimore
2   Tina       Ali   36          Miami
3   Jake    Milner   24        Douglas
4    Any     Cooze   73         Boston

In [63]:
df.rename(columns={'age':'나이'})

fn        ln  나이           city
0  Jason    Miller  43  San Francisco
1  Molly  jacobson  53      Baltimore
2   Tina       Ali  36          Miami
3   Jake    Milner  24        Douglas
4    Any     Cooze  73         Boston

In [67]:
s1 = pd.Series(range(1,6), index =['a','b','c','d','e'])
s2 = pd.Series(range(5,11), index = list('bcadef'))

print(s1)
print(s2)
print(s1 + s2)

s1 + s2

a    1
b    2
c    3
d    4
e    5
dtype: int64
b     5
c     6
a     7
d     8
e     9
f    10
dtype: int64
a     8.0
b     7.0
c     9.0
d    12.0
e    14.0
f     NaN
dtype: float64


a     8.0
b     7.0
c     9.0
d    12.0
e    14.0
f     NaN
dtype: float64

In [80]:
#df['age'] = df.age * range(5)
#df * range(5)

f = lambda x : x / 2
f(4)

print((lambda x : x + 1)(5))

list(map(lambda x : x * 2, [5]))
print(list(map(lambda x , y : x * 2 + y * 2, [5,10,5],[7,13,2])))



6
[24, 46, 14]


In [102]:
s = pd.Series(np.arange(10))
# 함수를 정해서 값을 넣어줄때 주로 사용한다
s.apply(lambda x : x + 1)

# 복잡한 함수의 내용을 적용하려고 할때
s.apply(lambda x : (x + 1) ** 2 - 5)

s.map({4 : 100, 59:100})

# 찾아서 변경
s = pd.Series(['female','male','male','female','female'])

s.map({'female' : 0, 'male' : 1})
s.replace({'female' : 0, 'male' : 1})

0    0
1    1
2    1
3    0
4    0
dtype: int64

In [110]:
raw_data = {
    'first_name' : ['Jason', 'Molly', 'Tina', 'Jake', 'Any'],
    'last_name' : ['Miller', 'jacobson', 'Ali', 'Milner', 'Cooze'],
    'age' : [43,53,36,24,73],
    'city' : ['San Francisco', 'Baltimore', 'Miami','Douglas','Boston']
}

df = pd.DataFrame(raw_data)
df

df.age.apply
# apply
# df.col.apply(함수) : 함수가 칼럼에 적용되서 적용

df.age.apply(lambda x : x**2)
df.age.sum()

df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))
df.index = ['a','b','c']
df.columns = ['가','나','다']
df.sum(axis=0)

가    12
나    15
다    18
dtype: int64

In [114]:
df.apply(sum) # df에 바로 apply(함수)를 적용하면 칼럼 전체에 함수가 적용
#df['가'].apply(sum) # df의 칼럼에 apply(함수) 적용하면 칼럼의 데이터 각각에 함수가 적용..

df['가'].apply(lambda x : x * 2)

a     2
b     8
c    14
Name: 가, dtype: int64

In [116]:
df.applymap(lambda x : x * (-1))

가  나  다
a -1 -2 -3
b -4 -5 -6
c -7 -8 -9

In [121]:
# pd.read_csv(csv file 경로)
# pd.read_excel(excel file 경로)
# pd.read_sql(sql query : select * from table 명)

wages = pd.read_csv('D:\BookExample_Python\Lecture03\Tranning\Backup\eda_data_files\wages.csv')
wages.head
wages.info()

wages.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   earn    1379 non-null   float64
 1   height  1379 non-null   float64
 2   sex     1379 non-null   object 
 3   race    1379 non-null   object 
 4   ed      1379 non-null   int64  
 5   age     1379 non-null   int64  
dtypes: float64(2), int64(2), object(2)
memory usage: 64.8+ KB


earn  height     sex   race  ed  age
1374  30173.380363   71.68    male  white  12   33
1375  24853.519514   61.31  female  white  18   86
1376  13710.671312   63.64  female  white  12   37
1377  95426.014410   71.65    male  white  12   54
1378   9575.461857   68.22    male  white  12   31

In [125]:
wages.race.unique()
wages.sex
wages.sex.unique()
# 'white' : 0, 'black' : 1, 'hispanic' : 2, 'other' : 3
wages.race

0       white
1       white
2       white
3       other
4       white
        ...  
1374    white
1375    white
1376    white
1377    white
1378    white
Name: race, Length: 1379, dtype: object

In [135]:
#wages.race.map({ i[1] : i[0] for i in dict(enumerate(list(wages.race.unique()))).items()})
wages['race'] = wages.race.replace({'white' : 0, 'black' : 1, 'hispanic' : 2, 'other' : 3})


0       0
1       0
2       0
3       1
4       0
       ..
1374    0
1375    0
1376    0
1377    0
1378    0
Name: race, Length: 1379, dtype: int64

In [139]:
from sklearn.preprocessing import LabelEncoder

# 라벨 Encoder
e = LabelEncoder()
e.fit_transform(wages.race)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
#df.groupby()
# Group By



In [146]:
data = {'Team' : ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'Giant', 'Kings', 'Kings', 'Riders', \
                 'Royals', 'Royals', 'Riders'],
       'Rank': [1,2,2,3,3,4,1,1,2,4,1,2],
       'Year' : [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
       'Points': [876,789,863,673,741,812,756,788,694,701,804,690]}
data

df = pd.DataFrame(data)

df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Giant     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [ ]:
# Team 별로 point의 총합을 구하시오

# 데이터를 그룹으로 묶는다
# 칼럼을 가져온다.
# 값을 계산한다.

df.groupby('Team')['Points'].sum()


In [147]:
# 연도별 최고 점수...

df.groupby('Year')['Points'].max()


Year
2014    876
2015    812
2016    756
2017    788
Name: Points, dtype: int64

In [148]:
# Team별 데이터 수
df.groupby('Team').count()

Rank  Year  Points
Team                      
Devils     2     2       2
Giant      1     1       1
Kings      3     3       3
Riders     4     4       4
Royals     2     2       2

In [152]:
# 데이터를 묶는 기준을 세분화... => 팀별, 연도별.. => Point의 평균값
# index가 복수 => multi index, heirachical index
# unstack() : 하위 index가 column으로 바뀌면서 index의 중복이 해소
df.groupby(['Team','Year'])['Points'].mean().unstack()

Year     2014   2015   2016   2017
Team                              
Devils  863.0  673.0    NaN    NaN
Giant     NaN  812.0    NaN    NaN
Kings   741.0    NaN  756.0  788.0
Riders  876.0  789.0  694.0  690.0
Royals  701.0  804.0    NaN    NaN

In [159]:
# groupby 객체 생성
grouped = df.groupby('Team')
grouped.Points.sum()

# get_group() : 그룹별 데이터를 리턴
grouped.get_group('Riders')

grouped.get_group('Kings')


Team  Rank  Year  Points
4  Kings     3  2014     741
6  Kings     1  2016     756
7  Kings     1  2017     788

In [161]:
# agg : groupby 객체에 함수를 다양하게 적용할 수 있음..
grouped = df.groupby('Team')
grouped.agg(['sum','mean','max'])

Rank                Year                    Points                 
        sum      mean max   sum         mean   max    sum        mean  max
Team                                                                      
Devils    5  2.500000   3  4029  2014.500000  2015   1536  768.000000  863
Giant     4  4.000000   4  2015  2015.000000  2015    812  812.000000  812
Kings     5  1.666667   3  6047  2015.666667  2017   2285  761.666667  788
Riders    7  1.750000   2  8062  2015.500000  2017   3049  762.250000  876
Royals    5  2.500000   4  4029  2014.500000  2015   1505  752.500000  804

In [163]:
df.head(2)

Team  Rank  Year  Points
0  Riders     1  2014     876
1  Riders     2  2015     789

In [164]:
grouped.agg({'Rank':'min','Points':'mean'})

Rank      Points
Team                    
Devils     2  768.000000
Giant      4  812.000000
Kings      1  761.666667
Riders     1  762.250000
Royals     1  752.500000

In [176]:
phone = pd.read_csv('eda_data_files\phone_data.csv')
phone.head(2)

index            date  duration  item    month   network network_type
0      0  15/10/14 06:58    34.429  data  2014-11      data         data
1      1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile

In [177]:
# item 별 통화시간의 합
phone.groupby('item')['duration'].sum()


item
call    92321.00
data     5164.35
sms       292.00
Name: duration, dtype: float64

In [178]:

# network별 평균 사용시간
phone.groupby('network')['duration'].mean()


network
Meteor        83.137931
Tesco        164.773810
Three        170.004651
Vodafone      68.697674
data          34.429000
landline     438.880952
special        1.000000
voicemail     65.740741
world          1.000000
Name: duration, dtype: float64

In [ ]:
# 연도를 제외한 월별 평균사용시간
phone.date.dropna()
# item별 시간대별 총 사용시간

In [186]:
phone.groupby('item')['duration'].sum()

# network별 평균 사용시간
phone.groupby('network')['duration'].mean()
# 연도를 제외한 월별 평균사용시간
phone.month.apply(lambda x : x.split('-')[1])
phone['sub_mon'] = phone.month.apply(lambda x : x.split('-')[1])
# 이미 존재하는 칼럼에 값을 할당하면 기존값을 덮어 쓴다
# 새로운 칼럼에 값을 할당하면 새로운 칼럼이 추가된다 => dict와 유사한 방식

phone.head()
phone.groupby('sub_mon')['duration'].mean()

# item별 시간대별 총 사용시간

sub_mon
01     88.894141
02    113.301453
03    225.251891
11    115.823657
12     93.260318
Name: duration, dtype: float64

In [197]:
phone['sub_time'] = phone.date.apply(lambda x : x.split()[1].split(':')[0])
phone.groupby('sub_time')['duration'].sum()

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.